apiVersion: v1
kind: Service
metadata:
  name: dotnet-webapi-service
  labels:
    app: dotnet-webapi
spec:
  selector:
    app: dotnet-webapi
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
  type: LoadBalancer
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: dotnet-webapi-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: ads-dental-api.azure.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: dotnet-webapi-service
            port:
              number: 80
