apiVersion: apps/v1
kind: Deployment
metadata:
  name: dotnet-webapi
  labels:
    app: dotnet-webapi
spec:
  replicas: 2
  selector:
    matchLabels:
      app: dotnet-webapi
  template:
    metadata:
      labels:
        app: dotnet-webapi
    spec:
      containers:
      - name: dotnet-webapi
        image: adsdentalacr.azurecr.io/dotnet-webapi:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "256Mi"
            cpu: "200m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        env:
        - name: ASPNETCORE_ENVIRONMENT
          value: "Production"
        - name: ASPNETCORE_URLS
          value: "http://+:80"
        livenessProbe:
          httpGet:
            path: /adsweb/api/v1/patients
            port: 80
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /adsweb/api/v1/patients
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 5
